### ISSUE TITLE
Don't work with rc2020-06-01

### ISSUE THREAD

**Issue by Laserlicht** [babs/dokuwiki-plugin-stlviewer#1]
Don't show STL's. :(

Also the plugin-manager shows:
"Update: Version 2020-04-25 steht zum Download bereit."
which is strange.

**Comment by babs** [comment]
Can you provide a little more feedback about "Don't show STL's" ?
I'm waiting for the stable release of hogfather.

**Comment by babs** [comment]
I've updated the way JS is called in 2020-06-20 version, it should be ok, can you confirm ?

**Comment by Laserlicht** [comment]
Thank you for the ultra fast response.

And sorry for the short description.

I can confirm. It work with the new version.
Thank you!
