### ISSUE TITLE
The requested URL /wiki/wiki/lib/exe/fetch.php was not found

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [babs/dokuwiki-plugin-stlviewer#3]
Hi,

would like to use the plugin for displaying STL files, but I only get the message that the file does not exist:
```
Not Found
The requested URL /wiki/wiki/lib/exe/fetch.php was not found on this server.
```
The link to the STL file is something like this:
```wiki//wiki/lib/exe/fetch.php?media=my:namespace:test.stl```
I use Release 2020-07-29 "Hogfather"

What can I do?

Greetings, 
Juergen

**Comment by babs** [comment]
Hi,

Isn't there a config issue on your doku setup ?
The plugin uses DOKU_URL variable which is global.
The hint is the double slash and the lack on one at the beginning.

**Comment by Juergen-aus-Zuendorf** [comment]
That's right, that's obviously where the problem lies. 

For comparison, here is the full link to a normal image and to an STL file:
`http://appsrv03/wiki/lib/exe/fetch.php?media=redaktionssystem:ccms:infprod:akat:spa:verschlussdeckel_quer_p1_p3.png`
`http://appsrv03/wiki//wiki/lib/exe/fetch.php?media=redaktionssystem:ccms:infprod:akat:wza:cx:test.stl`

I don't know how to read out the value of "DOKU_URL". If it helps could you please give me a hint for this?

**Comment by babs** [comment]
I think it's between your .htaccess and the settings page

**Comment by Juergen-aus-Zuendorf** [comment]
The parameter DOKU_URL is `http://appsrv03/wiki/`

**Comment by babs** [comment]
mines are refered as https://hostname//_media/3d_printing:creality:ender_3:ender_3_filament_guide.stl

**Comment by babs** [comment]
Try with rewrite enabled ?

**Comment by Juergen-aus-Zuendorf** [comment]
What do you mean with rewrite enabled ?

**Comment by babs** [comment]
to enable mod_rewrite in apache and activate userewrite as .htaccess in Advanced settings of dokuwiki

**Comment by babs** [comment]
Without rewrite my URL is https://hostname//lib/exe/fetch.php?media=3d_printing:creality:ender_3:ender_3_filament_guide.stl
And it works like a charm.
Double check your wiki config like basedir and baseurl.

**Comment by Juergen-aus-Zuendorf** [comment]
Sorry, but I can't change the parameter "userewrite", because this would make the wiki inaccessible without our IT also making settings on the server side. Unfortunately, I can't make this adjustment at the moment due to a lack of capacity in our IT.

Both parameters basedir and baseurl are empty.

**Comment by babs** [comment]
It should be an issue in your configuration, I tried without rewrite at all, and everything went fine.

**Comment by Juergen-aus-Zuendorf** [comment]
I've tested the same example in my test installation under XAMPP, and the result is the same:

`http://localhost/wiki//wiki/lib/exe/fetch.php?media=playground:test.stl`

**Comment by babs** [comment]
why is there wiki twice ?

**Comment by Juergen-aus-Zuendorf** [comment]
The same problem as above

**Comment by babs** [comment]
This portion is generated by doku wiki ENGINE, not the plugin, therefore there is an issue in the engine configuration, that's what I'm trying to tell you

**Comment by babs** [comment]
cf https://www.dokuwiki.org/devel:environment#doku

**Comment by Juergen-aus-Zuendorf** [comment]
The same problem as above

**Comment by Juergen-aus-Zuendorf** [comment]
What do you think about the following code in your syntax.php (from line 124 downwards)?
```
	/* Modification Line 124: */
	$urlmedia = DOKU_URL . "lib/exe/fetch.php?media=" . $opts['id'];
        if (isset($opts['noop'])) {
            $renderer->doc .= "<a href=\"" . $urlmedia . "\">".$opts['id']."</a>";
            return false;
        }
...
	/* Modification:
        $buff[] = "        filename: \"" . $urlmedia . "\"";		
```

**Comment by babs** [comment]
Issue is with rewrite mode the link is not lib/exe/fetch.php?media=mediaId anymore but /_media/mediaId. I think the issue lies at the conjunction in the middle of ml function and DOKU_URL usage.

**Comment by babs** [comment]
maybe abs at true without DOKU_URL ?

**Comment by Juergen-aus-Zuendorf** [comment]
In the plugin "filelist" there is a similar requirement, which is solved in this way:
```
class syntax_plugin_filelist extends DokuWiki_Syntax_Plugin {

    var $mediadir;
    var $is_odt_export = false;

    function __construct() {
        global $conf;
        $mediadir = $conf['mediadir'];
        if (!$this->_path_is_absolute($mediadir)) {
            $mediadir = DOKU_INC . '/' . $mediadir;
        }
        $this->mediadir = $this->_win_path_convert($this->_realpath($mediadir).'/');
    }
...
```
Perhaps it could help.

**Comment by babs** [comment]
I've to setup my dev env to check this.

**Comment by Juergen-aus-Zuendorf** [comment]
Or just another idea: the plugin "svgembed" works somewhat like yours for svg files.

**Comment by babs** [comment]
@Juergen-aus-Zuendorf your suggestion seems to work, I'll integrate it :)
