### ISSUE TITLE
Not working in an up-to-date dokuwiki

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [babs/dokuwiki-plugin-stlviewer#4]
Hi,

I have just installed your extension, and it seems that the rendering is not working anymore:

https://triglav.ouvaton.org/magus/doku.php?id=wiki:fanart:start

**Comment by babs** [comment]
Hi,

It seems that it's the same issue as #1 due to sub folder, I'll definitely have to take a look.

**Comment by Jacques-Olivier-Farcy** [comment]
Thanks anyway for this quick answer.
I hope you'll find the answer.

**Comment by babs** [comment]
You can monkey patch as explained in #1

**Comment by Jacques-Olivier-Farcy** [comment]
Not sure to understand what you are suggesting.
I am already with an up-to-date Dokuwiki

![image](https://user-images.githubusercontent.com/19731340/126340472-343264f1-bdaf-4a7c-a4e4-04ac53d49ba4.png)

**Comment by babs** [comment]
Sorry, I was referencing the wrong issue.
You can edit syntax.php of the deployed plugin and try what is suggested on 
https://github.com/babs/dokuwiki-plugin-stlviewer/issues/3#issuecomment-800402475 while I bootstrap a new instance to fix this.

**Comment by Jacques-Olivier-Farcy** [comment]
Hi,

I already tried these modifications, but it is not working.

Here is my modified syntax.php, maybe i did something wrong ?

[syntax.php.txt](https://github.com/babs/dokuwiki-plugin-stlviewer/files/6892106/syntax.php.txt)

**Comment by Jacques-Olivier-Farcy** [comment]
Hi there, any news ?

**Comment by babs** [comment]
I didn't had the time to bootstrap my new env to check that, so no :/
I hope soon.
